admin_produits:
    path:     /
    defaults: { _controller: "ProduitsBundle:Produit:index" }

admin_produits_show:
    path:     /{id}/show
    defaults: { _controller: "ProduitsBundle:Produit:show" }

admin_produits_new:
    path:     /new
    defaults: { _controller: "ProduitsBundle:Produit:new" }

admin_produits_create:
    path:     /create
    defaults: { _controller: "ProduitsBundle:Produit:create" }
    requirements: { _method: post }

admin_produits_edit:
    path:     /{id}/edit
    defaults: { _controller: "ProduitsBundle:Produit:edit" }

admin_produits_update:
    path:     /{id}/update
    defaults: { _controller: "ProduitsBundle:Produit:update" }
    requirements: { _method: post|put }

admin_produits_delete:
    path:     /{id}/delete
    defaults: { _controller: "ProduitsBundle:Produit:delete" }
    requirements: { _method: post|delete }
