<?php

namespace Pages\PagesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
	public function recherche($chaine) {
		$qb = $this->createQueryBuilder('alias')
			->select('alias')
			->where('alias.titre like :chaine')
			->orderBy('alias.id')
			->setParameter('chaine', '%'.$chaine.'%');
		return $qb->getQuery()->getResult();
	}
}