<?php

namespace Produits\ProduitsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AtelierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AtelierRepository extends EntityRepository
{
}
