<?php

namespace Produits\ProduitsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends EntityRepository
{
	public function controleFacture($utilisateur) {
		/*
		$qb = $this->createQueryBuilder('alias')
			->select('alias')
			->where('(alias.utilisateur.username = :utilisateur) and (alias.facture.reglee = 1)')
			->orderBy('alias.facture.id', 'DESC')
			->setMaxResults(1)
			->setParameter('utilisateur', $utilisateur);
		return $qb->getQuery()->getResult();
		*/
		return -2;
	}
}