<?php

namespace Produits\ProduitsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends EntityRepository {
	public function parCategorie($categorie) {
		$qb = $this->createQueryBuilder('alias')
			->select('alias')
			->where('alias.categorie = :categorie')
			->orderBy('alias.id')
			->setParameter('categorie', $categorie);
		return $qb->getQuery()->getResult();
	}
	public function parTableau($tableau) {
		if(count($tableau) > 0) {
			$qb = $this->createQueryBuilder('alias')
				->select('alias')
				->where('alias.id in (:tableau)')
				->setParameter('tableau', $tableau);
			return $qb->getQuery()->getResult();
		}
		else {
			return null;
		}
	}
}