<?php

namespace Proxies\__CG__\Produits\ProduitsBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Produit extends \Produits\ProduitsBundle\Entity\Produit implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setTitre($titre)
    {
        $this->__load();
        return parent::setTitre($titre);
    }

    public function getTitre()
    {
        $this->__load();
        return parent::getTitre();
    }

    public function setArticle($article)
    {
        $this->__load();
        return parent::setArticle($article);
    }

    public function getArticle()
    {
        $this->__load();
        return parent::getArticle();
    }

    public function setImage($image)
    {
        $this->__load();
        return parent::setImage($image);
    }

    public function getImage()
    {
        $this->__load();
        return parent::getImage();
    }

    public function setTarif($tarif)
    {
        $this->__load();
        return parent::setTarif($tarif);
    }

    public function getTarif()
    {
        $this->__load();
        return parent::getTarif();
    }

    public function setConfirme($confirme)
    {
        $this->__load();
        return parent::setConfirme($confirme);
    }

    public function getConfirme()
    {
        $this->__load();
        return parent::getConfirme();
    }

    public function setTva(\Produits\ProduitsBundle\Entity\Tva $tva)
    {
        $this->__load();
        return parent::setTva($tva);
    }

    public function getTva()
    {
        $this->__load();
        return parent::getTva();
    }

    public function setCategorie(\Produits\ProduitsBundle\Entity\Categorie $categorie)
    {
        $this->__load();
        return parent::setCategorie($categorie);
    }

    public function getCategorie()
    {
        $this->__load();
        return parent::getCategorie();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'titre', 'article', 'image', 'tarif', 'confirme', 'tva', 'categorie');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}