<?php

namespace Proxies\__CG__\Produits\ProduitsBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Poste extends \Produits\ProduitsBundle\Entity\Poste implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setNumeroPoste($numeroPoste)
    {
        $this->__load();
        return parent::setNumeroPoste($numeroPoste);
    }

    public function getNumeroPoste()
    {
        $this->__load();
        return parent::getNumeroPoste();
    }

    public function setCalendrier($calendrier)
    {
        $this->__load();
        return parent::setCalendrier($calendrier);
    }

    public function getCalendrier()
    {
        $this->__load();
        return parent::getCalendrier();
    }

    public function setAtelier(\Produits\ProduitsBundle\Entity\Atelier $atelier)
    {
        $this->__load();
        return parent::setAtelier($atelier);
    }

    public function getAtelier()
    {
        $this->__load();
        return parent::getAtelier();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'numeroPoste', 'calendrier', 'atelier');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}